version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install aws-sam-cli
      - cd sam-app

  pre_build:
    commands:
      - echo "Running sam build..."
      - sam build

  build:
    commands:
      - echo "Packing SAM template...."
      - sam package --output-template-file packaged.yaml --s3-bucket bucket-juan-images

artifacts:
  files:
    - packaged.yaml

