AWSTemplateFormatVersion: '2010-09-09'
Description: 'Mi primera plantilla de infraestructura como código'

Parameters:
  BucketNameParameter:
    Type: String
    Description: Nombre del bucket
    Default: bucket-jeg-polinube2

  InstanceName:
    Type: String
    Description: Nombre de la instancia
    Default: jeg-instance

Resources:

  BucketS3:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: !Ref BucketNameParameter

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: "*"
            
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

  EC2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e449927258d45bc4 
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd 
          aws s3 cp s3://${BucketNameParameter}/index.html /var/www/html/index.html
      Tags:
        - Key: Name
          Value: !Ref InstanceName

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir trafico HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: jeg-sg


Outputs:

  BucketArnExport:
    Description: ARN del bucket S3
    Value: !GetAtt BucketS3.Arn
    Export:
      Name: BucketS3-ARN